accounts/urls.py
from django.urls import path
from .views import doctor_signup_view, login_view, patient_signup_view, logout_view, user_profile_view,signup_options

urlpatterns = [
    path('signup/doctor/', doctor_signup_view, name='doctor_signup'),
    path('signup/patient/', patient_signup_view, name='patient_signup'),
    path('login/', login_view, name='login'),
    path('signup_options/', signup_options, name='signup_options'),
    path('logout/', logout_view, name='logout'),
    path('profile/', user_profile_view, name='profile'),
    
]

medical_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import home
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('og-admin/', admin.site.urls),
    path('',home, name='home'),
    path('accounts/',include('accounts.urls')),
    path('blog/',include('blogs_app.urls')),  
    path('booking/',include('booking_system.urls')),  
    
    # path('doctor_dashboard/', doctor_dashboard_view, name='doctor_dashboard'),
    # path('patient_dashboard/', patient_dashboard_view, name='patient_dashboard'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs_app/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='blog_images/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    summary = models.TextField()
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE) 
    is_draft = models.BooleanField(default=False)
    
    def __str__(self):
        return self.title

templates/appointment_confirmation.html
{% extends 'blog_base.html' %} {% block content %}
<section id="content" class="s-content">
  <!-- pageheader -->
  <div class="s-pageheader">
    <div class="row">
      <div class="column">
        <h2 class="mt-5">Appointment Confirmed</h2>
        <div class="flex d-flex">
          <h5 class="mt-1 mr-2">Doctor:</h5>
          <p>{{appointment.doctor.user.first_name}}</p>
        </div>
        <div class="flex d-flex">
          <h5 class="mt-1 mr-2">Speciality:</h5>
          <p>{{appointment.speciality}}</p>
        </div>
        <div class="flex d-flex">
          <h5 class="mt-1 mr-2">Date:</h5>
          <p>{{appointment.date}}</p>
        </div>
        <div class="flex d-flex">
          <h5 class="mt-1 mr-2">Time:</h5>
          <p>{{appointment.start_time}}</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
        crossorigin="anonymous"
    >
    {% block title %}
    
    {% endblock title %}
    
</head>
<body>
    <div>
        {% block content %}
        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/blog_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Doctor Dashboard{% endblock %}</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% comment %} <link rel="stylesheet" href="{% static 'css/vendor.css' %}"> {% endcomment %}

</head>
<body>
    <!-- Navigation Bar -->
    <header id="masthead" class="s-header">

        <div class="s-header__branding">
            <p class="site-title">
                Medical portal
            </p>
        </div>

        <div class="row s-header__navigation">

            <nav class="s-header__nav-wrap">
                
                
                    
                <h3 class="s-header__nav-heading">Navigate to</h3>

                <ul class="s-header__nav">
                    
                    <li><a href="{% url 'home' %}" title="">Home</a></li>
                 

                    
                    <li class="has-children">
                        <a href="" title="" class="">Categories</a>
                        <ul class="sub-menu">
                            {% for category in categories %}
                            <li><a href="{% url 'blogs_list' category.id %}">{{category.name}}</a></li>
                            {% endfor %}
                            
                        </ul>
                    </li>

                    
                    {% if user.is_authenticated and user.is_doctor %}
                    <li><a href="{% url 'create_blog' %}" title="">Create</a></li>
                    {% endif %}

                    {% if user.is_authenticated and user.is_doctor %}
                    <li><a href="{% url 'my_blogs' %}" title="">My Blogs</a></li>
                    {% endif %}
                    {% if user.is_authenticated and user.is_doctor %}
                    <li><a href="{% url 'doctor_appointments' %}" title="">Schedule</a></li>
                    {% endif %}
                    {% if user.is_authenticated and user.is_patient %}
                    <li><a href="{% url 'doctors_list' %}" title="">Doctors</a></li>
                    {% endif %}

                    
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'profile' %}" title="">Profile</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}" title="">login</a></li>
                    {% endif %}
                        
              

        
                </ul> <!-- end s-header__nav -->

            </nav> <!-- end s-header__nav-wrap -->

        </div> <!-- end s-header__navigation -->

       

        <a class="s-header__menu-toggle" href="#0"><span>Menu</span></a>
       

    </header> <!-- end s-header -->


    </nav>

    <!-- Main Content -->
    <div class="container ">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
     {% comment %} <script src="{% static 'js/plugins.js' %}"></script> {% endcomment %}
    {% comment %} <script src="{% static 'js/main.js' %}"></script>  {% endcomment %}

</body>
</html>

templates/blogs_list.html
{% extends 'blog_base.html' %}

{% block title %}Blogs on-{{category.name}}{% endblock %}

{% block content %}
<section id="content" class="s-content">


    <!-- pageheader -->
    <div class="s-pageheader">
        <div class="row">
            <div class="column large-12">
                
                {% if category %}
                    
                <h1 class="page-title">
                    <span class="page-title__small-type">Category:</span>
                    {{category}}
                </h1>
                {% endif %}
                    
            </div>
        </div>
    </div> <!-- end s-pageheader-->


    <!--  masonry -->
    <div id="bricks" class="bricks">

        <div class="masonry">

            <div class="bricks-wrapper" data-animate-block>

                <div class="grid-sizer"></div>
                <div class="row">
                {% for blog in blogs %}
                
                
                <div class="col-md-4">
                    <div class="card mb-4">
                        <img src="{{ blog.image.url }}" class="card-img-top" alt="{{ blog.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ blog.title }}</h5>
                            <p class="card-text">{{ blog.summary|truncatewords:15 }}</p>
                                
                            <a href="{% url 'blog_view' blog.id %}" class="btn btn-primary">Read More</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
                

            </div> <!-- end bricks-wrapper -->

        </div> <!-- end masonry-->



       
    </div> <!-- end bricks -->

</section> <!-- end s-content -->
{% endblock %}

templates/create_blog.html
{% extends "blog_base.html" %}
{% block title %}
<title>create-blog</title>
{% endblock title %}

{% block content %}
<section id="content" class="s-content">
<div class="container mt-2">
    <h2 style="margin: 0">Create Blog Post</h2>
    <form class="mt-3" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title</label>
            <input type="text" class="form-control" id="id_title" name="title" placeholder="Enter title">
        </div>
        <div class="form-group">
            <label for="id_image">Image</label>
            <input type="file" class="form-control-file" id="id_image" name="image" accept="image/*" onchange="previewImage(event)">
        </div>
        <div class="form-group col-md-4">
            <img id="image_preview" src="#" alt="Image Preview" style="display: none; max-width: 100%; height: auto;"/>
        </div>
        <div class="form-group">
            <label for="id_category">Category</label>
            <select class="form-control" id="id_category" name="category">
                {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_summary">Summary</label>
            <textarea class="form-control" id="id_summary" name="summary" rows="3" placeholder="Enter summary"></textarea>
        </div>
        <div class="form-group">
            <label for="id_content">Content</label>
            <textarea class="form-control" id="id_content" name="content" rows="5" placeholder="Enter content"></textarea>
        </div>
        <div class="form-group form-check m-3 mb-5">
            <input type="checkbox" class="form-check-input" id="id_is_draft" name="is_draft">
            <label class="form-check-label m-3" for="id_is_draft">Save as Draft</label>
        </div>
        <button type="submit" class="btn btn--primary">Submit</button>
    </form>
</div>

<script>
    function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function(){
            var output = document.getElementById('image_preview');
            output.src = reader.result;
            output.style.display = 'block';
        }
        reader.readAsDataURL(event.target.files[0]);
    }
    </script>

{% endblock content %}

templates/doctor_schedule.html
{% extends 'blog_base.html' %} {% block content %}

<section id="content" class="s-content">
  <!-- pageheader -->
  {% comment %} <div class="s-pageheader"> {% endcomment %}
    <div class="row">
      <div class="column">
        <div class="d-flex justify-content-between">
          <h1 class="mt-0">My Schedule</h1>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Start Time</th>
                    <th>Patient</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for appointment in appointments %}
                    <tr>
                        <td>{{ appointment.date }}</td>
                        <td>{{ appointment.start_time }}</td>
                        <td>{{ appointment.patient.get_full_name }}</td>
                        
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">No appointments found.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/doctors_list.html
{% extends 'blog_base.html' %} {% block content %}

<section id="content" class="s-content">
  <!-- pageheader -->
  {% comment %} <div class="s-pageheader"> {% endcomment %}
    <div class="row">
      <div class="column">
        <div class="d-flex justify-content-between">

          <h1 class="mt-0">List of Doctors</h1>
          <a class="btn btn-primary" href="{% url 'user_appointments' %}">My appointments</a>
        </div>
        {% for doctor in doctors %}
        <div class="col-md-12 mb-4">
          <div class="card">
            <div class="row g-0">
              <div class="col-md-4">
                {% if doctor.user.profile_picture %}
                <img
                  src="{{ doctor.user.profile_picture.url }}"
                  alt="{{ doctor.user.get_full_name }}"
                  class="img-fluid rounded-start mb-0"
                  style="
                    width: 300px;
                    height: 300px;
                    object-fit: cover;
                    object-position: center;
                    border-radius: 8px;
                  "
                />
                {% endif %}
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">
                    {{ doctor.user.first_name }} {{ doctor.user.last_name }}
                  </h5>
                  <p class="card-text">
                    <strong>Speciality:</strong> {{ doctor.speciality }}
                  </p>
                  {% comment %}
                  <p class="card-text">
                    <strong>Email:</strong> {{ doctor.user.email }}
                  </p>
                  {% endcomment %}
                  <a href="{% url 'book_appointment' doctor.id %}" class="btn btn--primary">Book Appointment</a>
                </div>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/home.html
{% extends 'blog_base.html' %} {% block title %}Home{% endblock %} 

{% block content %}
<section id="content" class="s-content">
    <!-- pageheader -->
    <div class="s-pageheader">
        <div class="row">
            <div class="column large-12">
                <h2 class="page-title">Latest Articles</h2>
            </div>
        </div>
    </div>
    <!-- end s-pageheader-->

    <!--  masonry -->
    <div id="bricks" class="bricks">
        <div class="masonry">
            <div class="bricks-wrapper" data-animate-block>
                <div class="grid-sizer"></div>

                <div class="row">
                    {% for blog in blogs %}

                    <div class="col-md-4">
                        <div class="card mb-4">
                            <img
                                src="{{ blog.image.url }}"
                                class="card-img-top"
                                alt="{{ blog.title }}"
                            />
                            <div class="card-body">
                                <div class="entry__meta">
                                    
                                    <span class="byline">
                                        By:{{ blog.author.first_name }}
                                    </span>
                                </div>
                                <h5 class="card-title mt-1">{{ blog.title }}</h5>
                                <p class="card-text">
                                    {{ blog.summary|truncatewords:15 }}
                                </p>
                                <a
                                    href="{% url 'blog_view' blog.id %}"
                                    class="btn btn-primary"
                                    >Read More</a
                                >
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- end bricks-wrapper -->
        </div>
        <!-- end masonry-->
    </div>
    <!-- end bricks -->
</section>

{% endblock content %}

templates/landingpage.html
{% extends "base.html" %}
{% block title %}
<title>Medical Portal</title>
{% endblock title %}

{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center" >
        <h1 class="my-5">Medical Portal</h1>
        <ul class="navbar-nav mt-3">
            <a class="btn btn-primary mb-4" href="{% url 'doctor_signup' %}" role="button">Sign Up as Doctor</a>
            <a class="btn btn-primary mb-4" href="{% url 'patient_signup' %}" role="button">Sign Up as Patient</a>
            <a class="btn btn-success" href="{% url 'login' %}" role="button">Login</a>
        </ul>

</div>
{% endblock content %}

templates/my_appointments.html
{% extends 'blog_base.html' %} {% block content %}

<section id="content" class="s-content">
  <!-- pageheader -->
  {% comment %} <div class="s-pageheader"> {% endcomment %}
    <div class="row">
      <div class="column">
        <div class="d-flex justify-content-between">
          <h1 class="mt-0">My appointments</h1>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Start Time</th>
                    <th>Doctor</th>
                    <th>Speciality</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for appointment in appointments %}
                    <tr>
                        <td>{{ appointment.date }}</td>
                        <td>{{ appointment.start_time }}</td>
                        <td>{{ appointment.doctor.user.get_full_name }}</td>
                        <td>{{ appointment.speciality }}</td>
                        <td>
                          <a class="btn btn-danger mb-0" href="{% url 'cancel_appointment' appointment.id %}">Cancel</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">No appointments found.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/my_blogs.html
{% extends 'blog_base.html' %}

{% block title %}Blogs on-{{category.name}}{% endblock %}

{% block content %}
<section id="content" class="s-content">


    <!-- pageheader -->
    <div class="s-pageheader">
        <div class="row">
            <div class="column large-12">
                
                {% if category %}
                    
                <h1 class="page-title">
                    <span class="page-title__small-type">Category:</span>
                    {{category}}
                </h1>
                {% endif %}
                    
            </div>
        </div>
    </div> <!-- end s-pageheader-->


    <!--  masonry -->
    <div id="bricks" class="bricks">

        <div class="masonry">

            <div class="bricks-wrapper" data-animate-block>

                <div class="grid-sizer"></div>
                <div class="row">
                {% for blog in blogs %}
                
                
                <div class="col-md-4">
                    <div class="card mb-4">
                        <img src="{{ blog.image.url }}" class="card-img-top" alt="{{ blog.title }}">
                        <div class="card-body">
                            
                            <h5 class="card-title">{{ blog.title }} 
                            </h5>
                            {% if blog.is_draft %}
                            <span class="badge badge-secondary">Draft</span>
                            {% endif %}
                            <p class="card-text">{{ blog.summary|truncatewords:15 }}</p>
                            
                            
                            
                    
                            
                                
                            <a href="{% url 'blog_view' blog.id %}" class="btn btn-primary">Read More</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
                

            </div> <!-- end bricks-wrapper -->

        </div> <!-- end masonry-->



       
    </div> <!-- end bricks -->

</section> <!-- end s-content -->
{% endblock %}

templates/patient_dashboard.html
{% extends 'base.html' %}

{% block title %}
<title>Dashboard</title>
{% endblock title %}
{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid d-flex">
            <h1 class="navbar-brand mx-5" href="#">Patient dashboard</h1>
            <a class="btn btn-danger mx-5" href="{% url 'logout' %}" role="button">Logout</a>  
    </div>
</nav>
<div class="container pt-5">
    <h2>Profile</h2>
    <div class="card mt-4">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4 text-center">
                    {% if user.profile_picture %}
                        <img src="{{ user.profile_picture.url }}" alt="Profile Picture" class="img-thumbnail">
                    {% else %}
                        <img src="https://via.placeholder.com/150" alt="Profile Picture" class="img-thumbnail">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th>First Name</th>
                                <td>{{ user.first_name }}</td>
                            </tr>
                            <tr>
                                <th>Last Name</th>
                                <td>{{ user.last_name }}</td>
                            </tr>
                            <tr>
                                <th>Email</th>
                                <td>{{ user.email }}</td>
                            </tr>
                            <tr>
                                <th>Username</th>
                                <td>{{ user.username }}</td>
                            </tr>
                            <tr>
                                <th>Address</th>
                                <td>
                                    {{ user.address_line1 }}<br>
                                    {{ user.city }}, {{ user.state }}<br>
                                    {{ user.pincode }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/signupoptionspage.html
{% extends "blog_base.html" %}
{% block title %}
Medical Portal- SignIn Options
{% endblock title %}

{% block content %}
<section id="content" class="s-content">


    <!-- pageheader -->
    <div class="s-pageheader">
        <div class="row">
            <div class="column">
<div class="container d-flex flex-column justify-content-center align-items-center" >
        <ul class="navbar-nav mt-3">
            <a class="btn btn-primary mb-4" href="{% url 'doctor_signup' %}" role="button">Sign Up as Doctor</a>
            <a class="btn btn-primary mb-4" href="{% url 'patient_signup' %}" role="button">Sign Up as Patient</a>
            <a class="btn btn-success" href="{% url 'login' %}" role="button">Login</a>
        </ul>

</div>
</div>
</div>
</div>
{% endblock content %}

templates/user_profile.html
{% extends 'blog_base.html' %}

{% block content %}

<div class="container pt-5">
    <h2>Profile</h2>
    <div class="card mt-4">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4 text-center">
                    {% if user.profile_picture %}
                        <img class="img-fluid rounded-start square-image" src="{{ user.profile_picture.url }}" alt="Profile Picture"  >
                    {% else %}
                        <img src="https://via.placeholder.com/150" alt="Profile Picture" class="img-thumbnail">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th>First Name</th>
                                <td>{{ user.first_name }}</td>
                            </tr>
                            <tr>
                                <th>Last Name</th>
                                <td>{{ user.last_name }}</td>
                            </tr>
                            <tr>
                                <th>Email</th>
                                <td>{{ user.email }}</td>
                            </tr>
                            <tr>
                                <th>Username</th>
                                <td>{{ user.username }}</td>
                            </tr>
                            <tr>
                                <th>Address</th>
                                <td>
                                    {{ user.address_line1 }}<br>
                                    {{ user.city }}, {{ user.state }}<br>
                                    {{ user.pincode }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="container-fluid d-flex">
        
                        <a class="btn btn--primary" href="{% url 'logout' %}" role="button">Logout</a>  
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}